on: push

jobs: 
  npm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pwd
    - run: ls
    - run: npm --version
    - run: npm install
    - run: npm run build