on: push

jobs: 
  npm-build:
    name: Build React Project
    runs-on: ubuntu-latest
    steps:
    - name: Read repository code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
      
    - name: Build the project
      run: npm run build